"""Streamlit app."""

import duckdb
import streamlit as st

from dotenv import load_dotenv

DATABASE = "FG_DWH"
TABLE = "dbt_staging.obt_fct_tbl"

load_dotenv()

con = duckdb.connect(database=f"md:{DATABASE}", read_only=True)

st.title("Green Grid Geeks")

# all power generated by year-month
query = f"""
SELECT
    CONCAT(year_value, month_value) as year_month,
    SUM(source_value) AS megawatts
FROM {TABLE}
WHERE date_value < '2025-01-01'
GROUP BY CONCAT(year_value, month_value)
ORDER BY CONCAT(year_value, month_value);
"""
df = con.execute(query).df()
st.subheader("All Power Production")
st.line_chart(df, x="year_month")

# power generated by source by year-month
source_query = "SELECT source_name FROM dbt_staging.dim_sources;"
sources = [source[0] for source in con.execute(source_query).fetchall()]
source = st.selectbox("Power source:", sources)
st.subheader(f"{source}")
query = f"""
SELECT
    CONCAT(year_value, month_value) as year_month,
    SUM(source_value) AS megawatts
FROM {TABLE}
WHERE date_value < '2025-01-01'
  AND source_name = '{source}'
GROUP BY CONCAT(year_value, month_value)
ORDER BY CONCAT(year_value, month_value);
"""
df = con.execute(query).df()
st.line_chart(df, x="year_month")
