gggfingrid:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "md:FG_DWH?motherduck_token={{env_var('MOTHERDUCK_TOKEN')}}"
      schema: 'analytics'
      extensions:
        - httpfs
        - parquet